### ISSUE TITLE
Extend to find closest N neighbors

### ISSUE THREAD

**Issue by cdcseacave** [jbehley/octree#13]
This is fast and works great for radius search. Is it also possible to implement a fast search for closest N neighbors with this octree structure?

**Comment by jbehley** [comment]
my octree relies on knowing the maximum possible radius and therefore i can just stop descending if I find an octant that is inside the search ball.

for k nearest neighbors the initial maximum radius is infinity; therefore one descends into the leaf containing the query.
one tries then to find k neighbors and then one can possibly use the inverse of abovementioned idea: if the search does not touch a quadrant, one does not need to descend into this subtree. However, the savings might be negligible, since the standard traversal does something similar.

I thought about k nearest neighbors, but had not really an idea. Thus, to answer your question, I don't know how to use my strategy to speed up k nearest neighbor search.
