### ISSUE TITLE
Enhancement: Eigen support

### ISSUE THREAD

**Issue by sheikware** [jbehley/octree#14]
First, I would like to thank you for the library. It is a very nice templated octree implementation.

Based on my own requirements, I needed support for Eigen::Matrix3Xd for the data structure (didn't want to make a std::vector of Eigen::Vector3d and wrap Eigen::Vector3d with the accessor traits.

I forked the library and made my own updates (also tried to clean-up the cmake build to make it an interface library to better install the header file). Unfortunately I couldn't find a good way to keep it templated with ContainterT and PointT and support Eigen Matrix... though I was tempted to use the nanoflann approach. 

With Eigen in my testing (MSVC build) it seems to actually run faster than using the Point3f structs in the examples. 

No real issue, just want to let you know that the code is there. 

Thanks!

**Comment by jbehley** [comment]
thanks for your comment. See also #8 for other improvements.

I was experimenting with eigen but only for the individual points. there was not a big win over a 3 float point, since gcc replaces many operations in O3 with SSE.

Storing all points in a single matrix, I did not consider this. However, my feeling is that gcc is pretty good with O3, which might not bring the same gains under ubuntu. But I might clone your repo and try it under ubuntu. It's pretty long time ago that I touched this code.

Thanks for your feedback. And good to hear that my tree still is used somewhere. :)
