### ISSUE TITLE
Bug in overlaps method

### ISSUE THREAD

**Issue by SylvainBertrand** [jbehley/octree#3]
Hi!
Thanks a lot for sharing your code!!

I believe there is a bug with the method overlaps.
More precisely in Octree.hpp line 722:  "if (x < o->extent || y < o->extent || z < o->extent) return true;"
The concept seems correct in 2D, however in 3D, at least two of the three conditions have to be valid at the same time to be able to return true.

A simple example revealing the bug is the following:
query = (x = 0.025, y = 0.025, 0.025)
radius = 0.025
octant_center = (x = 0.025, y = -0.025, z = -0.025)
octant_extent = 0.025

When displaying the octant and the sphere, it is clear that the sphere does not overlap with the octant although the overlaps method returns true.

**Comment by jbehley** [comment]
Hi @SylvainBertrand,

thanks for your interest in my Octree implementation and thanks for pointing out this issue! You are  totally correct and that's a case I didn't considered in my derivation in the paper. I'm working on a fix and will hopefully fix this issue soon. So stay tuned.

From my initial experiments and understanding of this issue, it seems that it should still result in the correct neighbor results, but should have an influence on the runtime, of course. Currently, it seems like that I'm just testing more then necessary. So after fixing this issue, the runtime should be better. 

But let's first see if I find a simple and elegant fix for this issue without altering the code to much.

**Comment by jbehley** [comment]
I've found the problem and my conceptual error.

You were totally right. The simplification to two-dimensional space resulted in missing a special case for edges of the octant. However, the fix was pretty simple after some drawing. ;)

Hopefully, this resolves also your problems and might even make the code a little bit more efficient. However, the additional needed operations in the overlap test could outweigh the performance gain by not inspecting all octants.

However, I will see if I find the time to re-run and plot the experiments from the paper.
