### ISSUE TITLE
Stack overlow - there are no maximum depth termination conditions

### ISSUE THREAD

**Issue by sphet** [jbehley/octree#6]
First of all, thank you for this great work.

I am encountering stack overflow conditions using point clouds that are generally sparsely distributed but highly dense in one specific area. I have 650,000 points - but there is one node that ends up with ~50 points in a very dense region, causing infinite calls to createOctant(). Because there is no maximum depth termination, it seems to go on forever. Is this an expected pathological case? Eventually the extent of the octants being created is zero - it isn't clear to me why. Are you doing aggressive regression testing that I can plug my data into?

**Comment by jbehley** [comment]
Also thanks for your interest in my octree implementation and for reporting this issue.

The overflow happens due to my stopping criterion for creation of octants. In the current implementation I just check for the number of points inside a octant and if this drops below `bucketSize`, I stop creating octants. A possible solution would be to increase the bucket size to a large value, but this would also result in octants with fewer points to be unnecessary large.

To avoid the problem in your use case, I just added a additional parameter `minExtent` which specifies the minimum extent of leaf octants. Thus, you can now specify  this value to avoid an infinite generation of octants.

Hope that helps to solve your problem.

**Comment by sphet** [comment]
Thank you - this seems to solve the recursion issue in my test cases
